# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['jcatch_plugin/main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'selenium.webdriver.chrome.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.chrome.options',
        'webdriver_manager',
        'webdriver_manager.chrome',
        'webdriver_manager.core',
        'webdriver_manager.core.manager',
        'webdriver_manager.core.driver',
        'webdriver_manager.core.utils',
        'webdriver_manager.core.http',
        'PIL',
        'PIL.Image',
        'PIL.ImageFont',
        'PIL.ImageDraw',
        'pydantic',
        'pydantic.core',
        'pydantic.dataclasses',
        'bs4',
        'bs4.builder',
        'lxml',
        'lxml.etree',
        'lxml.html',
        'lxml.html.clean',
        'dotenv',
        'dotenv.main',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='jcatch',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
